server:
  http_listen_port: 3100

ingester:
  chunk_idle_period: 5m
  chunk_retain_period: 1h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

schema_config:
  configs:
    - from: 2020-01-01
      store: boltdb
      object_store: filesystem
      schema: v11
