version: '3.8'
services:
  mysql_sno_api:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE="${MYSQL_DATABASE}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    env_file: ".env"

  sno_api_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SNO_API_BACKEND_PORT}:${SNO_API_BACKEND_PORT}"
    depends_on:
      - mysql_sno_api
    networks:
      - backend
    env_file: ".env"

networks:
  backend:

volumes:
  db-data:
